import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <title>Hansika Perera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='/assests/logo.png' />

        <style>
          @import url('https://fonts.googleapis.com/css2?family=Lobster&family=Raleway:wght@600&family=Ubuntu&display=swap');
        </style>

      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        
      </main>
    </>
  )
}
