import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Logo from "../public/assests/logo.png"
import PImg1 from "../public/assests/img1.png"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <title>Hansika Perera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel='icon' href='/assests/logo.png' />

        <style>
          @import url('https://fonts.googleapis.com/css2?family=Lobster&family=Raleway:wght@600&family=Ubuntu&display=swap');
        </style>

      </Head>
      <header>
      <nav className='flex justify-between'>
        
        <Image
          src={Logo}
          alt="logo"
          width='85'
          height='10'
          className="my-8 mx-10 inline-block"
        />
        <ul className='font-raleway font-semibold  flex justify-end mx-16 my-12'>
          <li className='mx-8'>HOME</li>
          <li className='mx-8'>ABOUT ME</li>
          <li className='mx-8'>SKILS</li>
          <li className='mx-8'>PROJECTS</li>
          <li className='mx-8'>CONTACT</li>
        </ul>
        
       
       </nav>
      </header>
      <main >
      
      </main>
    </>
  )
}
